[build]
  publish = "library"
  command = ""

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"

[[headers]]
  for = "/entities/*"
  [headers.values]
    Cache-Control = "public, max-age=86400"

[[headers]]
  for = "/chapters/*"
  [headers.values]
    Cache-Control = "public, max-age=86400"

[[headers]]
  for = "/word_index/*"
  [headers.values]
    Cache-Control = "public, max-age=86400"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
